[package]
name = "N_i_Kit_OS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checkssl = "0.2.0"
http = "0.2.9"
reqwest = "0.11.22"
sqlite = { version = "0.31.1" }
url = "2.4.1"
